---
# Crash Course Python for Data Science - Intro to Python  
---
# 06 - Numpy
---



## STOP! BEFORE GOING ANY FURTHER...  

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples.



### Import Numpy as Np

In [3]:
# Make sure you run this cell first
import numpy as np
print('NumPy imported!')

NumPy imported!


### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [4]:
x = np.random.randint(0, 100, (5, 3))
print(x)


[[ 3 60 90]
 [79 38 21]
 [17 66 19]
 [66 13  5]
 [14 46 77]]


In [5]:
#@title Double click here for a sample solution

x = np.random.randint(0,100, (5,3))
x

array([[20, 24, 25],
       [77, 41, 75],
       [ 8, 11, 81],
       [70, 38,  2],
       [58, 58,  9]], dtype=int32)

### Array practice

In [6]:
# Return the first row:
print(x[0,])  # first row

### YOUR CODE GOES HERE ###

[20 24 25]


In [7]:
#@title Double click here for a sample solution

# Return the first row:
x[0,]

array([20, 24, 25], dtype=int32)

In [8]:
# Return last column
print(x[:, -1])  # last column

### YOUR CODE GOES HERE ###

[25 75 81  2  9]


In [9]:
#@title Double click here for a sample solution

# Return last column
x[:, -1]

array([25, 75, 81,  2,  9], dtype=int32)

In [10]:
# Return the third column values from the 4th and 5th rows
print(x[3:5, 2])  #third column ,4th and 5th rows

### YOUR CODE GOES HERE ###

[2 9]


In [11]:
#@title Double click here for a sample solution

# Return the third column values from the 4th and 5th rows
x[3:5,2]

array([2, 9], dtype=int32)

In [12]:
# Multiply every value in the array by 2

### YOUR CODE GOES HERE ###

In [13]:
#@title Double click here for a sample solution

# Multiply every value in the array by 2
x*2

array([[ 40,  48,  50],
       [154,  82, 150],
       [ 16,  22, 162],
       [140,  76,   4],
       [116, 116,  18]], dtype=int32)

In [14]:
# Divide every value by 3

### YOUR CODE GOES HERE ###

In [15]:
#@title Double click here for a sample solution

# Divide every value by 3
x/3

array([[ 6.66666667,  8.        ,  8.33333333],
       [25.66666667, 13.66666667, 25.        ],
       [ 2.66666667,  3.66666667, 27.        ],
       [23.33333333, 12.66666667,  0.66666667],
       [19.33333333, 19.33333333,  3.        ]])

In [16]:
# Increase the values in the first row by 12

### YOUR CODE GOES HERE ###

In [17]:
#@title Double click here for a sample solution

# Increase the values in the first row by 12
x[0,] = x[0,] + 12
x

array([[32, 36, 37],
       [77, 41, 75],
       [ 8, 11, 81],
       [70, 38,  2],
       [58, 58,  9]], dtype=int32)

In [18]:
# Calculate the mean of the first column

### YOUR CODE GOES HERE ###

In [19]:
#@title Double click here for a sample solution

# Calculate the mean of the first column
x[:,0].mean()

np.float64(49.0)

In [20]:
# Calculate the median of the array after removing the 2 smallest values in the array

### YOUR CODE GOES HERE ###

In [21]:
#@title Double click here for a sample solution

# Calculate the median of the array after removing the 2 smallest values in the array
x1 = np.delete(x, x.argmin())
x1 = np.delete(x1, x1.argmin())
np.median(x1)


np.float64(41.0)

In [22]:
# Calculate the standard deviation of the first 3 rows

### YOUR CODE GOES HERE ###

In [23]:
#@title Double click here for a sample solution

# Calculate the standard deviation of the first 3 rows
np.std(x[:3],)

np.float64(25.969117461484803)

In [24]:
# Return values in the second column greater than 25

### YOUR CODE GOES HERE ###

In [25]:
#@title Double click here for a sample solution

# Return values in the second column greater than 25
print("Values bigger than 25 on the second column =", x[:,1][x[:,1]>25])

Values bigger than 25 on the second column = [36 41 38 58]


In [26]:
# Return values in the array under 40

### YOUR CODE GOES HERE ###

In [27]:
#@title Double click here for a sample solution

# Return values in the array under 40
print("Values under 40 in array =", x[x<40])

Values under 40 in array = [32 36 37  8 11 38  2  9]
